# Generated by Django 3.0 on 2023-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_resume',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('0', 'Guest')], default='0', max_length=5),
        ),
    ]
