# Generated by Django 3.0 on 2023-08-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapp', '0002_auto_20230815_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('0', 'Guest'), ('1', 'Applicant'), ('2', 'Recruiter')], default='0', max_length=5),
        ),
    ]
