# Generated by Django 3.0 on 2023-08-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapp', '0003_auto_20230815_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_resume',
            field=models.BooleanField(default=False),
        ),
    ]
