# Generated by Django 3.0 on 2023-08-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapp', '0004_auto_20230816_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_resume',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_type',
            field=models.CharField(choices=[('0', 'Guest'), ('1', 'Admin')], default='0', max_length=5),
        ),
    ]
