# Generated by Django 3.0 on 2023-08-24 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapp', '0006_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='usd',
        ),
    ]
