# Generated by Django 3.0 on 2023-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapp', '0008_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='dateandtime',
        ),
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='time',
            field=models.TimeField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
    ]
